name: Embedded Build

on:
  push: {}
  pull_request: {}
    
jobs:

  build-windows:

    runs-on: windows-2019
    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]

    steps:
      - uses: actions/checkout@v2

      - name: Retrieve submodules
        shell: cmd
        run: git submodule update --init --recursive

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build Python
        shell: cmd
        run: |
          cd Scripts
          call BuildPythonForWindows.bat --ci
          cd ..
          mkdir cmake-build-release
          cd cmake-build-release
          cmake ..

      - name: Build DearPyGui
        shell: cmd
        run: |
          cmake --build cmake-build-release --config Release

      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: dearpygui-binary-0.6.415-${{ matrix.python-version }}
          path: D:/a/DearPyGui/DearPyGui/cmake-build-release/*
